# Generated by Django 4.2.4 on 2023-09-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='econtact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eemail',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ename',
        ),
        migrations.AddField(
            model_name='employee',
            name='empresa_terceira',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='fornrcedores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='funcionarios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='nome_setor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='produtos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
