# Generated by Django 4.2.4 on 2023-09-10 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_employee_econtact_remove_employee_eemail_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='fornrcedores',
            new_name='fornecedores',
        ),
        migrations.AlterField(
            model_name='employee',
            name='nome_setor',
            field=models.CharField(default=30, max_length=30),
            preserve_default=False,
        ),
    ]
