# Generated by Django 3.2.7 on 2021-10-05 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dados_setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_setor', models.CharField(max_length=20)),
                ('funcionarios', models.CharField(max_length=100)),
                ('fornecedores', models.EmailField(max_length=254)),
                ('produtos', models.CharField(max_length=15)),
                ('empresa_terceira', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'dados_setor',
            },
        ),
    ]
