# Generated by Django 4.2.4 on 2023-09-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados_setor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dados_setor',
            name='empresa_terceira',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados_setor',
            name='fornecedores',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados_setor',
            name='funcionarios',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados_setor',
            name='nome_setor',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dados_setor',
            name='produtos',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
